# The mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory (24 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/TeamPneumatic/pnc-repressurized/issues"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://minecraft.curseforge.com/projects/pneumaticcraft-repressurized"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile=""
# A text field displayed in the mod UI
credits=""
# A text field displayed in the mod UI
authors="desht, MineMaarten"
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]] #mandatory
# The modid of the mod
modId="pneumaticcraft" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${version}" #mandatory
 # A display name for the mod
displayName="PneumaticCraft: Repressurized"
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://raw.githubusercontent.com/TeamPneumatic/pnc-repressurized/1.14/release_info.json" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
PneumaticCraft: Repressurized: doing cool stuff with compressed air.
'''

[[dependencies.pneumaticcraft]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.2.3,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.pneumaticcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.pneumaticcraft]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.1-26,)"
    ordering="NONE"
    side="BOTH"