license="GNU GPLv3"
modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/TeamPneumatic/pnc-repressurized/issues"
displayURL="https://minecraft.curseforge.com/projects/pneumaticcraft-repressurized"
logoFile="pncr_logo.png"
credits=""
authors="desht, MineMaarten"

[[mods]]
    modId="pneumaticcraft"
    version="${version}"
    displayName="PneumaticCraft: Repressurized"
    updateJSONURL="https://raw.githubusercontent.com/TeamPneumatic/pnc-repressurized/1.18.2/release_info.json" #optional
    description='''
PneumaticCraft: Repressurized: doing cool stuff with compressed air.'''

[[dependencies.pneumaticcraft]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.pneumaticcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.pneumaticcraft]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.18.2-66,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pneumaticcraft]]
    modId="jei"
    mandatory=false
    versionRange="[9.5.0,)"
    ordering="NONE"
    side="BOTH"
