license="GNU GPLv3"
modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/TeamPneumatic/pnc-repressurized/issues"
displayURL="https://minecraft.curseforge.com/projects/pneumaticcraft-repressurized"
#logoFile=""
credits=""
authors="desht, MineMaarten"

[[mods]]
    modId="pneumaticcraft"
    version="${version}"
    displayName="PneumaticCraft: Repressurized"
    updateJSONURL="https://raw.githubusercontent.com/TeamPneumatic/pnc-repressurized/1.16.3/release_info.json" #optional
    description='''
PneumaticCraft: Repressurized: doing cool stuff with compressed air.'''

[[dependencies.pneumaticcraft]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34.1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
#[[dependencies.pneumaticcraft]]
#    modId="patchouli"
#    mandatory=false
#    versionRange="[1.15.2-1.2-32,)"
#    ordering="NONE"
#    side="BOTH"
#[[dependencies.pneumaticcraft]]
#    modId="computercraft"
#    mandatory=false
#    versionRange="[1.88.1,)"
#    ordering="NONE"
#    side="BOTH"
[[dependencies.pneumaticcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.16.4]"
    ordering="NONE"
    side="BOTH"
