name: "Build a release"

# Controls when the action will run. Triggers the workflow on push or pull request
# events for the branches listed
on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Export release tag as environment variable
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean gradle
        run: ./gradlew clean --no-daemon --max-workers 1
      - name: Remove any generated assets/data
        run: rm -rf ./src/generated
      - name: Generate assets
        run: ./gradlew runData --no-daemon --max-workers 1 || test -d ./src/generated/resources/.cache
      - name: Validate assets
        run: test -d ./src/generated -a -d ./src/generated/resources/.cache
      - name: Build with Gradle
        run: ./gradlew build --no-daemon --max-workers 1
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Set up mod metadata
        id: mod_meta
        run: |
          echo "::set-output name=mod_version::$(grep ^mod_version_ ./gradle.properties | cut -d= -f2 | tr '\012' '.' | sed -e 's/\.$//')"
          echo "::set-output name=mc_version::$(grep ^mc_version ./gradle.properties | cut -d= -f2)"
          echo "::set-output name=changelog::$(./scripts/extract_changes.sh)"
      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: pncr-dist-${{ github.ref_name }}-${{ steps.mod_meta.outputs.mod_version}}-${{ github.run_number }}
          path: build/libs/
      - name: Publish to Modrinth
        env:
          CHANGELOG: ${{ steps.mod_meta.outputs.changelog }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          BUILD_NUMBER: ${{ github.run_number }}
        run: ./gradlew modrinth --no-daemon --max-workers 1
      - name: Publish to Curseforge
        env:
          CHANGELOG: ${{ steps.mod_meta.outputs.changelog }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          BUILD_NUMBER: ${{ github.run_number }}
        run: ./gradlew curseforge --no-daemon --max-workers 1
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if:
          env.DISCORD_WEBHOOK != null
        with:
          args: 'Release made for project {{ EVENT_PAYLOAD.repository.full_name }} (Minecraft ${{ steps.mod_meta.outputs.mc_version}}): ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.'